import requests
from utils.data_reader import load_json_data

# Load configuration data
data = load_json_data()
BASE_URL = data["api_url"]

def test_get_users():
    """Test 1: GET request - List users and validate structure."""
    url = f"{BASE_URL}/users"
    response = requests.get(url)
    
    # Assert status code
    assert response.status_code == 200, f"Expected 200, got {response.status_code}"
    
    # Parse JSON
    res_json = response.json()
    
    # Assert response is a list
    assert isinstance(res_json, list), "Expected response to be a list of users"
    assert len(res_json) > 0, "Expected user list to not be empty"
    
    # Validate structure of the first user item
    first_user = res_json[0]
    expected_keys = ["id", "name", "username", "email", "address"]
    for key in expected_keys:
        assert key in first_user, f"User item missing key '{key}'"

def test_create_user():
    """Test 2: POST request - Create a user and validate response."""
    url = f"{BASE_URL}/users"
    payload = {
        "name": "Mailen Barba",
        "username": "mailen",
        "email": "mailen@example.com"
    }
    response = requests.post(url, json=payload)
    
    # Assert status code (201 Created)
    assert response.status_code == 201, f"Expected 201, got {response.status_code}"
    
    res_json = response.json()
    
    # Validate response attributes match payload
    assert res_json["name"] == payload["name"], f"Expected name '{payload['name']}', got '{res_json['name']}'"
    assert res_json["username"] == payload["username"], f"Expected username '{payload['username']}', got '{res_json['username']}'"
    assert res_json["email"] == payload["email"], f"Expected email '{payload['email']}', got '{res_json['email']}'"
    
    # Validate autogenerated ID
    assert "id" in res_json, "Response missing autogenerated 'id'"

def test_delete_user():
    """Test 3: DELETE request - Delete a user and validate status code."""
    url = f"{BASE_URL}/users/1"
    response = requests.delete(url)
    
    # Assert status code (200 OK for JSONPlaceholder)
    assert response.status_code == 200, f"Expected 200, got {response.status_code}"

def test_chaining_get_user_details():
    """Test 4: Request Chaining (GET -> GET) - Extract ID from list, then fetch details."""
    # Step 1: GET users list
    list_url = f"{BASE_URL}/users"
    list_response = requests.get(list_url)
    assert list_response.status_code == 200
    
    # Extract first user details
    users = list_response.json()
    assert len(users) > 0, "No users found"
    target_user = users[0]
    target_id = target_user["id"]
    target_email = target_user["email"]
    target_name = target_user["name"]
    
    # Step 2: GET details of the specific user
    detail_url = f"{BASE_URL}/users/{target_id}"
    detail_response = requests.get(detail_url)
    
    assert detail_response.status_code == 200, f"Expected 200, got {detail_response.status_code}"
    user_detail = detail_response.json()
    
    # Assert data matches original user
    assert user_detail["id"] == target_id, f"Expected ID {target_id}, got {user_detail['id']}"
    assert user_detail["email"] == target_email, f"Expected email {target_email}, got {user_detail['email']}"
    assert user_detail["name"] == target_name, f"Expected name {target_name}, got {user_detail['name']}"

def test_chaining_read_update_delete():
    """Test 5: Request Chaining (GET -> PUT -> DELETE) - Fetch, update, and clean up a user."""
    # Step 1: GET existing user to retrieve details
    user_url = f"{BASE_URL}/users/1"
    get_response = requests.get(user_url)
    assert get_response.status_code == 200
    
    user_data = get_response.json()
    original_name = user_data["name"]
    
    # Step 2: PUT to update the user name and details
    update_payload = {
        "name": f"{original_name} Updated",
        "username": user_data["username"],
        "email": user_data["email"]
    }
    put_response = requests.put(user_url, json=update_payload)
    assert put_response.status_code == 200, f"Expected 200, got {put_response.status_code}"
    
    put_json = put_response.json()
    assert put_json["name"] == update_payload["name"]
    
    # Step 3: DELETE to remove the user
    delete_response = requests.delete(user_url)
    assert delete_response.status_code == 200, f"Expected 200, got {delete_response.status_code}"
