import requests
from utils.data_reader import load_json_data
from utils.logger import get_logger

# Set up API logger
logger = get_logger("API_Tests")

# Load configuration data
data = load_json_data()
BASE_URL = data["api_url"]

def test_get_users():
    """Test 1: GET request - List users and validate structure."""
    logger.info("--- STARTING TEST: test_get_users ---")
    url = f"{BASE_URL}/users"
    logger.info(f"Sending GET request to: {url}")
    response = requests.get(url)
    
    logger.info(f"Response status received: {response.status_code}")
    assert response.status_code == 200, f"Expected 200, got {response.status_code}"
    
    res_json = response.json()
    
    logger.info("Verifying response is a list and contains items")
    assert isinstance(res_json, list), "Expected response to be a list of users"
    assert len(res_json) > 0, "Expected user list to not be empty"
    
    logger.info("Verifying keys on first user item")
    first_user = res_json[0]
    expected_keys = ["id", "name", "username", "email", "address"]
    for key in expected_keys:
        assert key in first_user, f"User item missing key '{key}'"
    logger.info("--- TEST PASSED: test_get_users ---")

def test_create_user():
    """Test 2: POST request - Create a user and validate response."""
    logger.info("--- STARTING TEST: test_create_user ---")
    url = f"{BASE_URL}/users"
    payload = {
        "name": "Mailen Barba",
        "username": "mailen",
        "email": "mailen@example.com"
    }
    logger.info(f"Sending POST request to: {url} with payload: {payload}")
    response = requests.post(url, json=payload)
    
    logger.info(f"Response status received: {response.status_code}")
    assert response.status_code == 201, f"Expected 201, got {response.status_code}"
    
    res_json = response.json()
    logger.info("Verifying user fields match request payload")
    assert res_json["name"] == payload["name"], f"Expected name '{payload['name']}', got '{res_json['name']}'"
    assert res_json["username"] == payload["username"], f"Expected username '{payload['username']}', got '{res_json['username']}'"
    assert res_json["email"] == payload["email"], f"Expected email '{payload['email']}', got '{res_json['email']}'"
    
    logger.info(f"Verifying autogenerated field 'id': {res_json.get('id')}")
    assert "id" in res_json, "Response missing autogenerated 'id'"
    logger.info("--- TEST PASSED: test_create_user ---")

def test_delete_user():
    """Test 3: DELETE request - Delete a user and validate status code."""
    logger.info("--- STARTING TEST: test_delete_user ---")
    url = f"{BASE_URL}/users/1"
    logger.info(f"Sending DELETE request to: {url}")
    response = requests.delete(url)
    
    logger.info(f"Response status received: {response.status_code}")
    assert response.status_code == 200, f"Expected 200, got {response.status_code}"
    logger.info("--- TEST PASSED: test_delete_user ---")

def test_chaining_get_user_details():
    """Test 4: Request Chaining (GET -> GET) - Extract ID from list, then fetch details."""
    logger.info("--- STARTING TEST: test_chaining_get_user_details ---")
    
    # Step 1: GET users list
    list_url = f"{BASE_URL}/users"
    logger.info(f"[Chaining Step 1] Sending GET request to: {list_url}")
    list_response = requests.get(list_url)
    assert list_response.status_code == 200
    
    users = list_response.json()
    assert len(users) > 0, "No users found"
    
    # Extract first user details
    target_user = users[0]
    target_id = target_user["id"]
    target_email = target_user["email"]
    target_name = target_user["name"]
    logger.info(f"[Chaining Step 1] Extracted user ID: {target_id}, Name: '{target_name}', Email: '{target_email}'")
    
    # Step 2: GET details of the specific user
    detail_url = f"{BASE_URL}/users/{target_id}"
    logger.info(f"[Chaining Step 2] Sending GET request to: {detail_url}")
    detail_response = requests.get(detail_url)
    
    logger.info(f"[Chaining Step 2] Response status received: {detail_response.status_code}")
    assert detail_response.status_code == 200, f"Expected 200, got {detail_response.status_code}"
    
    user_detail = detail_response.json()
    logger.info("[Chaining Step 2] Validating returned user details match step 1 extraction")
    assert user_detail["id"] == target_id, f"Expected ID {target_id}, got {user_detail['id']}"
    assert user_detail["email"] == target_email, f"Expected email {target_email}, got {user_detail['email']}"
    assert user_detail["name"] == target_name, f"Expected name {target_name}, got {user_detail['name']}"
    logger.info("--- TEST PASSED: test_chaining_get_user_details ---")

def test_chaining_read_update_delete():
    """Test 5: Request Chaining (GET -> PUT -> DELETE) - Fetch, update, and clean up a user."""
    logger.info("--- STARTING TEST: test_chaining_read_update_delete ---")
    
    # Step 1: GET user 1 to get baseline data
    user_url = f"{BASE_URL}/users/1"
    logger.info(f"[Chaining Step 1] Fetching user 1 details from: {user_url}")
    get_response = requests.get(user_url)
    assert get_response.status_code == 200
    
    user_data = get_response.json()
    original_name = user_data["name"]
    logger.info(f"[Chaining Step 1] Extracted user name: '{original_name}'")
    
    # Step 2: PUT to update name
    update_payload = {
        "name": f"{original_name} Updated",
        "username": user_data["username"],
        "email": user_data["email"]
    }
    logger.info(f"[Chaining Step 2] Sending PUT request to {user_url} with payload: {update_payload}")
    put_response = requests.put(user_url, json=update_payload)
    
    logger.info(f"[Chaining Step 2] Response status received: {put_response.status_code}")
    assert put_response.status_code == 200, f"Expected 200, got {put_response.status_code}"
    
    put_json = put_response.json()
    logger.info("Verifying PUT name updates correctly")
    assert put_json["name"] == update_payload["name"]
    
    # Step 3: DELETE to remove resource
    logger.info(f"[Chaining Step 3] Sending DELETE request to: {user_url}")
    delete_response = requests.delete(user_url)
    
    logger.info(f"[Chaining Step 3] Response status received: {delete_response.status_code}")
    assert delete_response.status_code == 200, f"Expected 200, got {delete_response.status_code}"
    logger.info("--- TEST PASSED: test_chaining_read_update_delete ---")
